### ISSUE TITLE
Build fails with NoRegionError

### ISSUE THREAD

**Issue by CloudNiner** [azavea/pfb-network-connectivity#555]
The `update_job_definitions.py` file fails with the following exception:
```
Creating network "awsbatch_default" with the default driver
Traceback (most recent call last):
  File "update_job_definition.py", line 50, in <module>
    main()
  File "update_job_definition.py", line 38, in main
    client = boto3.client('batch')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 71, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 281, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 354, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by CloudNiner** [comment]
It's unclear how this was working before, since we haven't changed boto versions in the docker container that runs the `update_job_definitions.py` file. 

However, the root issue is that our Jenkins `.aws/config` file had improperly named ini section headers. According to the [boto3 documentation](http://boto3.readthedocs.io/en/latest/guide/configuration.html#aws-config-file) for the `.aws/config` file, section headers aside from `[default]` must include the `profile ` prefix in their name. Our pfb profile section header was `[pfb]` when it should be `[profile pfb]`. I updated the section header name on the jenkins host and re-ran the build, and we're back to green again. 

There were no build failures on PR builds because we only communicate with AWS in `./scripts/infra`, which is not run on PR builds.

**Comment by CloudNiner** [comment]
Closing since this issue was fixed by the changes above.
