### ISSUE TITLE
Django ValidationError when trying to run analysis locally

### ISSUE THREAD

**Issue by beckymasond** [azavea/pfb-network-connectivity#568]
macOS 10.13.4
VirtualBox 5.2.10
Vagrant 2.0.4
Using AWS CLI and AWS credentials.

I followed the instructions provided (first on the main page, then on the "Running the Analysis Locally" page) to run the analysis locally using the given test files for Boulder. The steps were:
- configure AWS credentials
- copy all.example file
- copy job queue names into 'all' file
- run ./script/setup
- ssh into VM
- configure s3 buckets
- run ./scripts/run-local-analysis https://s3.amazonaws.com/test-pfb-inputs/boulder/boulder.zip co 08

The analysis starts to execute then fails with the error detailed below.

LOG:  database system was shut down at 2018-04-26 19:26:40 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
/opt/pfb/analysis /
Updating job status: IMPORTING Downloading shapefile
Traceback (most recent call last):
  File "/opt/pfb/django/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/pfb/django/pfb_analysis/management/commands/update_status.py", line 18, in handle
    job = AnalysisJob.objects.get(pk=options['job_id'])
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 441, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 373, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/where.py", line 79, in as_sql
    sql, params = compiler.compile(child)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 373, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 170, in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 103, in process_rhs
    return self.get_db_prep_lookup(value, connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 196, in get_db_prep_lookup
    [get_db_prep_value(value, connection, prepared=True)]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 2387, in get_db_prep_value
    value = self.to_python(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 2401, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: [u"'local-job-2018-04-26-1926' is not a valid UUID."]
Updating job status: ERROR Failed See job logs for more details.

**Comment by CloudNiner** [comment]
Closing, this is addressed by the updated local analysis instructions added in #581
