### ISSUE TITLE
S3 error on local analysis run during results re-import

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#637]
Running a local analysis job fails on the Shapefile results re-import step with an S3 error.

<Details>
<AnalysisJob: EXPORTING Dunwoody>: Loaded overall_scores from /data/output/2abefe94-068b-4b0a-a7f6-8970280154a1/neighborhood_overall_scores.csv
[2018-12-27 15:59:34 +0000] [940] [INFO] Running import for analysis job 2abefe94-068b-4b0a-a7f6-8970280154a1.
[2018-12-27 15:59:34 +0000] [940] [INFO] Importing results back from shapefile: results/2abefe94-068b-4b0a-a7f6-8970280154a1/neighborhood_census_blocks.zip
[2018-12-27 15:59:34 +0000] [940] [ERROR] Error importing <class 'pfb_analysis.models.CensusBlocksResults'> shapefile for job: 2abefe94-068b-4b0a-a7f6-8970280154a1
Traceback (most recent call last):
  File "/opt/pfb/django/pfb_analysis/management/commands/import_results_shapefiles.py", line 64, in import_shapefile
    import_tmpdir = geom_from_results_url(s3_job_url(job, shpfile_name))
  File "/opt/pfb/django/pfb_analysis/management/commands/import_results_shapefiles.py", line 48, in geom_from_results_url
    local_zipfile)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 130, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
[2018-12-27 15:59:34 +0000] [940] [INFO] Importing results back from shapefile: results/2abefe94-068b-4b0a-a7f6-8970280154a1/neighborhood_ways.zip
[2018-12-27 15:59:34 +0000] [940] [ERROR] Error importing <class 'pfb_analysis.models.NeighborhoodWaysResults'> shapefile for job: 2abefe94-068b-4b0a-a7f6-8970280154a1
Traceback (most recent call last):
  File "/opt/pfb/django/pfb_analysis/management/commands/import_results_shapefiles.py", line 64, in import_shapefile
    import_tmpdir = geom_from_results_url(s3_job_url(job, shpfile_name))
  File "/opt/pfb/django/pfb_analysis/management/commands/import_results_shapefiles.py", line 48, in geom_from_results_url
    local_zipfile)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 130, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
Updating job status: EXPORTING Uploading results
</Details>

The results re-import then succeeds on either re-running the `export_connectivity.sh` script directly within the analysis container after the analysis run exits, or by re-running the entire analysis job without clearing out the existing results.

Connects #607

**Comment by CloudNiner** [comment]
Interesting. If we're running a local analysis job, then PFB_JOB_ID should be unset and we shouldn't want to import the geoms into postgres since we're running an analysis independently of the remaining app infrastructure. If that is the case, then [this check](https://github.com/azavea/pfb-network-connectivity/pull/607/files#diff-c83186a453339753169f5930e74d7095R4) should apply like it does for all the other Django related commands that don't run for local analyses.

**Comment by flibbertigibbet** [comment]
We should be able to continue running local analyses that integrate with the front-end; that's part of the testing workflow. The `PFB_JOB_ID` is set for the [logged local analysis command](https://github.com/azavea/pfb-network-connectivity/blob/92d506ee7e77b0729a9dbafe33afde7b61ec86bc/src/django/pfb_analysis/models.py#L691) and so should be expected locally, if not required.

**Comment by CloudNiner** [comment]
Ah. Might be a misunderstanding based on overloaded terminology. We've been referring to a "local analysis job" as one that is run on the local docker container and does not interface with the Django app in anyway. It simply outputs the result files to a local directory on the filesystem.

We've then been referring to "development analysis jobs" or "analysis jobs" as jobs that are run in the development environment, triggered through the Django app.

The analysis job container and scripts in the development environment should support both workflows. It sounds like the S3 not found error this issue is referring to was triggered via a development analysis job triggered through the Django app, correct?

**Comment by flibbertigibbet** [comment]
The job was initiated via the API analysis job endpoint, which then logs the local analysis docker command to invoke as I linked to above, which the developer has to manually start, as has been our development environment workflow for some time. What you're calling here a "development analysis job" involves running that provided command (with job ID) for what you're calling a "local analysis job," which needs to be executable with or without the job ID.

It looks like the job ID on the environment simply isn't getting passed through as expected in #607 from `utils.sh` to the import management command, perhaps because the command arguments need to be quoted.
